"""
Pipeline tests.

Tests the full VoicePipeline with real providers — Whisper STT,
Chatterbox TTS, Claude LLM, and Silero VAD.

Requirements:
    - ANTHROPIC_API_KEY set in environment
    - faster-whisper installed
    - chatterbox-tts installed
    - silero-vad installed
    - tests/fixtures/speech.raw must exist (generated by setup script below)

Generate speech fixture:
    mkdir -p tests/fixtures
    python -c "
    from gtts import gTTS
    import subprocess
    tts = gTTS('hello how are you doing today', lang='en')
    tts.save('/tmp/speech.mp3')
    subprocess.run(['ffmpeg', '-i', '/tmp/speech.mp3',
        '-ar', '16000', '-ac', '1', '-f', 'f32le',
        'tests/fixtures/speech.raw'], check=True)
    "

VAD note:
    Pipeline tests disable VAD (vad.enabled=False).
    VAD correctness is fully covered in tests/unit/test_vad.py.
    Pipeline tests focus on pipeline orchestration — STT, LLM, TTS
    working together correctly, not on VAD filtering behaviour.

Silence note:
    Whisper hallucination on silence ('Thank you.', 'you', etc) is
    suppressed via no_speech_threshold=0.6 in WhisperSTT.transcribe().
    Pure silence with those settings returns empty transcript.
"""
import asyncio
import os
import pathlib
import time

import numpy as np
import pytest
# add at the very top after imports
from dotenv import load_dotenv
load_dotenv()   # loads .env from current directory automatically
from voicekit.config import VoiceConfig, STTConfig, TTSConfig, VADConfig, LLMConfig
from voicekit.pipeline import VoicePipeline

SAMPLE_RATE = 16000
CHUNK_SAMPLES = 1600   # 100ms at 16kHz

# module-level shared pipeline — models load once for all tests
_shared_pipeline = None

def make_config() -> VoiceConfig:
    return VoiceConfig(
        project="test",
        stt=STTConfig(model="whisper", variant="tiny"),
        tts=TTSConfig(model="chatterbox-turbo", voice="default"),
        vad=VADConfig(
            enabled=False,    # disabled — VAD tested in test_vad.py
            sensitivity=0.5
        ),
        llm=LLMConfig(
            provider="anthropic",
            model="claude-haiku-4-5",
            api_key=os.environ.get("ANTHROPIC_API_KEY", ""),
        ),
        system_prompt=(
            "You are a helpful assistant. "
            "Reply in one short sentence only."
        ),
    )

@pytest.fixture
async def pipeline():
    """
    Load pipeline once for all tests via module-level cache.
    Whisper tiny + Chatterbox take ~30s on first load.
    Subsequent tests reuse the same loaded instance.
    VAD state is reset before each test.
    """
    global _shared_pipeline
    if _shared_pipeline is None:
        p = VoicePipeline(make_config())
        await p.load()
        _shared_pipeline = p

    # reset VAD state before each test even though VAD is disabled
    # keeps the instance clean between tests
    _shared_pipeline.vad.reset_states()

    return _shared_pipeline

async def make_silence_queue(duration_seconds: float = 1.0) -> asyncio.Queue:
    """Queue of pure silence chunks."""
    queue: asyncio.Queue = asyncio.Queue()
    num_chunks = int(duration_seconds * SAMPLE_RATE / CHUNK_SAMPLES)
    for _ in range(num_chunks):
        await queue.put(np.zeros(CHUNK_SAMPLES, dtype=np.float32))
    return queue

async def make_real_audio_queue() -> asyncio.Queue:
    """
    Load real speech audio from fixture file.
    Fixture generated by gTTS + ffmpeg — actual human speech converted
    to 16kHz float32 PCM. Whisper transcribes this accurately.
    Falls back to silence if fixture not found.
    """
    fixture = pathlib.Path("tests/fixtures/speech.raw")
    queue: asyncio.Queue = asyncio.Queue()

    if fixture.exists():
        audio = np.frombuffer(fixture.read_bytes(), dtype=np.float32)
    else:
        pytest.skip(
            "tests/fixtures/speech.raw not found. "
            "Generate it with: "
            "mkdir -p tests/fixtures && "
            "python -c \"from gtts import gTTS; import subprocess; "
            "tts = gTTS('hello how are you doing today', lang='en'); "
            "tts.save('/tmp/speech.mp3'); "
            "subprocess.run(['ffmpeg', '-i', '/tmp/speech.mp3', "
            "'-ar', '16000', '-ac', '1', '-f', 'f32le', "
            "'tests/fixtures/speech.raw'], check=True)\""
        )

    for i in range(0, len(audio), CHUNK_SAMPLES):
        chunk = audio[i:i + CHUNK_SAMPLES]
        if len(chunk) < CHUNK_SAMPLES:
            chunk = np.pad(chunk, (0, CHUNK_SAMPLES - len(chunk)))
        await queue.put(chunk)

    return queue


#  load tests 
@pytest.mark.asyncio
async def test_pipeline_loads_successfully():
    p = VoicePipeline(make_config())
    await p.load()
    health = await p.health()
    assert health["stt"] is True
    assert health["tts"] is True
    assert health["loaded"] is True


@pytest.mark.asyncio
async def test_run_turn_before_load_raises_error():
    p = VoicePipeline(make_config())
    audio_in: asyncio.Queue = asyncio.Queue()
    audio_out: asyncio.Queue = asyncio.Queue()
    with pytest.raises(RuntimeError) as exc:
        await p.run_turn(audio_in, audio_out)
    assert "load()" in str(exc.value)


#  silence tests 
@pytest.mark.asyncio
async def test_silence_produces_no_transcript(pipeline):
    """
    Pure silence sent to Whisper must return empty transcript.
    Whisper's no_speech_threshold=0.6 suppresses hallucinations.
    This is critical — hallucinated responses waste LLM tokens
    and produce unsolicited agent responses.
    """
    audio_in = await make_silence_queue(duration_seconds=1.0)
    audio_out: asyncio.Queue = asyncio.Queue()

    metrics = await pipeline.run_turn(audio_in, audio_out)

    assert metrics.transcript == "", (
        f"Whisper hallucinated on silence: '{metrics.transcript}'. "
        f"Increase no_speech_threshold in WhisperSTT.transcribe() "
        f"or set log_prob_threshold to a less negative value."
    )
    assert audio_out.empty(), (
        "Silence produced audio output — pipeline should stop "
        "when transcript is empty."
    )


#  real speech tests 
@pytest.mark.asyncio
async def test_real_speech_produces_transcript(pipeline):
    """
    Real speech audio (from gTTS fixture) must produce a transcript.
    Uses actual human speech converted to 16kHz float32 PCM.
    """
    audio_in = await make_real_audio_queue()
    audio_out: asyncio.Queue = asyncio.Queue()

    metrics = await pipeline.run_turn(audio_in, audio_out)

    assert metrics.transcript, (
        "Whisper returned empty transcript for real speech audio. "
        "Check that the fixture file contains valid 16kHz float32 PCM audio."
    )


@pytest.mark.asyncio
async def test_real_speech_produces_audio_output(pipeline):
    """Full pipeline: real speech → Whisper → Claude → Chatterbox → audio."""
    audio_in = await make_real_audio_queue()
    audio_out: asyncio.Queue = asyncio.Queue()

    metrics = await pipeline.run_turn(audio_in, audio_out)

    assert metrics.transcript, "No transcript produced"
    assert metrics.response, "No LLM response produced"
    assert not audio_out.empty(), "No audio output produced"


#  metrics tests 
@pytest.mark.asyncio
async def test_metrics_populated(pipeline):
    audio_in = await make_real_audio_queue()
    audio_out: asyncio.Queue = asyncio.Queue()

    metrics = await pipeline.run_turn(audio_in, audio_out)

    if metrics.transcript:
        assert metrics.stt_ms > 0
        assert metrics.llm_first_token_ms > 0
        assert metrics.tts_first_chunk_ms > 0
        assert metrics.total_ms > 0
        assert metrics.total_ms >= metrics.stt_ms


#  history tests 
@pytest.mark.asyncio
async def test_conversation_history_accumulates(pipeline):
    """History grows by 2 entries per successful turn."""
    initial_length = len(pipeline.history)

    audio_in = await make_real_audio_queue()
    audio_out: asyncio.Queue = asyncio.Queue()
    await pipeline.run_turn(audio_in, audio_out)

    if len(pipeline.history) > initial_length:
        assert len(pipeline.history) == initial_length + 2, (
            f"Expected {initial_length + 2} history entries, "
            f"got {len(pipeline.history)}"
        )


@pytest.mark.asyncio
async def test_history_has_correct_roles(pipeline):
    initial_length = len(pipeline.history)

    audio_in = await make_real_audio_queue()
    audio_out: asyncio.Queue = asyncio.Queue()
    await pipeline.run_turn(audio_in, audio_out)

    if len(pipeline.history) > initial_length:
        user_turn = pipeline.history[initial_length]
        assistant_turn = pipeline.history[initial_length + 1]
        assert user_turn["role"] == "user"
        assert assistant_turn["role"] == "assistant"


#  streaming cascade test 
@pytest.mark.asyncio
async def test_first_audio_arrives_before_pipeline_completes(pipeline):
    """
    The most important pipeline architectural test.

    LLM and TTS must run concurrently — first audio chunk must arrive
    before pipeline.run_turn() returns. If audio only arrives after
    the pipeline completes, LLM and TTS are running sequentially
    which breaks the streaming cascade.
    """
    audio_in = await make_real_audio_queue()
    audio_out: asyncio.Queue = asyncio.Queue()

    first_audio_time: list[float] = []

    async def monitor():
        while True:
            try:
                await asyncio.wait_for(audio_out.get(), timeout=60.0)
                if not first_audio_time:
                    first_audio_time.append(time.perf_counter())
                    return
            except asyncio.TimeoutError:
                return

    pipeline_task = asyncio.create_task(
        pipeline.run_turn(audio_in, audio_out)
    )
    monitor_task = asyncio.create_task(monitor())

    await pipeline_task
    pipeline_end = time.perf_counter()
    await monitor_task

    if first_audio_time:
        assert first_audio_time[0] < pipeline_end, (
            "First audio arrived after pipeline completed. "
            "LLM and TTS are not running concurrently — "
            "streaming cascade is broken."
        )